H: 36
RRHH_mensual:
- 3361
- 3361
- 3361
VC: 114471
beta: 0.2264
buffer_caja: 0
ciclo_op:
- 180
- 120
- 90
com_l: 0.01
com_v: 0.01
commercial_productivity_lag: 0
g_adm: 711
g_max_suavizado: 0.25
liquidity_policy:
  type: none
meta: 20
rem_l: 1500
rem_v: 1123
servicios:
- A_base:
  - 20
  - 5
  - 5
  - 6
  - 7
  - 6
  - 5
  - 4
  - 7
  - 12
  - 10
  - 9
  alpha: 0.87
  c_min: 8000
  c_u: 10.53
  churn_anual:
  - 0.22
  - 0.14
  - 0.07
  frecuencia: 1
  nombre: Sesiones_Blended
  ticket: 238.1
  u_max: 10000
solver:
  name: cbc
  time_limit: 120
  verbose: false
sup: 99
tax: 0.125
