H: 36
RRHH_mensual:
- 7681
- 8811
- 8811
VC: 146850
beta: 0.25595
buffer_caja: 0
ciclo_op:
- 180
- 120
- 90
com_l: 0.05
com_v: 0.2
commercial_productivity_lag: 0
g_adm: 1922
g_max_suavizado: 0.25
liquidity_policy:
  type: none
meta: 20
rem_l: 1500
rem_v: 1111
servicios:
- A_base:
  - 1
  - 2
  - 3
  - 5
  - 5
  - 7
  - 7
  - 9
  - 9
  - 10
  - 11
  - 14
  alpha: 0.76
  c_min: 5000
  c_u: 97
  churn_anual:
  - 0.1
  - 0.1
  - 0.1
  frecuencia: 1
  nombre: Vino_Blended
  ticket: 357.7
  u_max: 50
- A_base:
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  alpha: 0.95
  c_min: 200
  c_u: 5
  churn_anual:
  - 0.1
  - 0.1
  - 0.1
  frecuencia: 1
  nombre: Licencias_Software
  ticket: 50
  u_max: 200
solver:
  name: cbc
  time_limit: 120
  verbose: false
sup: 99
tax: 0.125
