H: 38
RRHH_mensual:
- 7622
- 28083
- 41528
VC: 243039
beta: 0.3155
buffer_caja: 0
ciclo_op:
- 180
- 120
- 90
com_l: 0.04
com_v: 0.08
commercial_productivity_lag: 0
g_adm: 741
g_max_suavizado: 0.25
liquidity_policy:
  type: none
meta: 5
rem_l: 2222
rem_v: 1111
servicios:
- A_base:
  - 3
  - 3
  - 4
  - 5
  - 6
  - 6
  - 6
  - 7
  - 7
  - 8
  - 8
  - 9
  alpha: 0.85
  c_min: 2222
  c_u: 11.11
  churn_anual:
  - 0.23
  - 0.09
  - 0.06
  frecuencia: 1
  nombre: SaaS_Recurrente
  ticket: 1400
  u_max: 100
- A_base:
  - 0
  - 0
  - 0
  - 0
  - 1
  - 1
  - 1
  - 1
  - 1
  - 2
  - 2
  - 1
  alpha: 0.95
  c_min: 3000
  c_u: 11.11
  churn_anual:
  - 0.0
  - 0.0
  - 0.0
  frecuencia: 1
  nombre: SaaS_Enterprise
  ticket: 5500
  u_max: 30
solver:
  name: cbc
  time_limit: 120
  verbose: false
sup: 5
tax: 0.125
