# -*- coding: utf-8 -*-
"""Optimizacion_plan_crecimiento_acelerado_V3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19YD22wH0Vo9_SAf-Qyo5lj43NXhQ2ek2

# Modelo de optimización para un plan de crecimiento acelerado

Este notebook implementa una primera versión funcional del modelo de optimización desarrollado para planificar el crecimiento acelerado de una startup.

Mantiene la lógica separada de:
* flujo de clientes
* flujo de servicios
* flujo de ingresos

Luego incorpora costos operacionales, CAC gastos de administración, caja y valorización.

A continuación se presenta el modelo matemático formal:

### Conjuntos

\begin{align*}
T &: \text{Períodos mensuales}, \quad t = 1,\dots,H \\
T^{base} &\subseteq T: \text{Períodos con adquisición fijada, usualmente meses 1--12} \\
S &: \text{Servicios o líneas de servicio}, \quad s \in S \\
\tau &\in T: \text{Cohorte de adquisición}, \quad \tau \leq t
\end{align*}

### Parámetros

\begin{align*}
A_{s,t}^{base} &: \text{Adquisición base del servicio } s \text{ en } t \in T^{base} \\[2mm]
Churn_{s,t} &: \text{Tasa de pérdida de clientes del servicio } s \text{ en } t \\[2mm]
\phi_{s,\tau,t} &: \text{Supervivencia acumulada de la cohorte } \tau \text{ del servicio } s \text{ hasta } t \\[1mm]
\phi_{s,\tau,t} &= \prod_{c=\tau+1}^{t} (1-Churn_{s,c}) \\[2mm]
f_s &: \text{Frecuencia de recompra del servicio } s \\[2mm]
\delta_{s,\tau,t} &\in \{0,1\}: \text{Indicador de recompra de la cohorte } \tau \text{ en } t \\[1mm]
\delta_{s,\tau,t} &=
\begin{cases}
1, & \text{si } t>\tau \text{ y } (t-\tau)\equiv 0 \pmod{f_s} \\
0, & \text{en otro caso}
\end{cases} \\[2mm]
\alpha_{s,t} &: \text{Porcentaje de clientes elegibles del servicio } s \text{ que recompran en } t \\[2mm]
Ticket_s &: \text{Ticket promedio del servicio } s \\[2mm]
meta &: \text{Clientes captados por vendedor por período} \\
sup &: \text{Cantidad de vendedores supervisados por líder} \\
rem_v &: \text{Remuneración mensual por vendedor} \\
rem_l &: \text{Remuneración mensual por líder} \\
com_v, com_l &: \text{Comisiones comerciales} \\[2mm]
c_s^u &: \text{Costo unitario promedio del servicio } s \\
c_s^{min} &: \text{Costo mínimo por escalón operacional del servicio } s \\
u_s^{max} &: \text{Capacidad máxima por escalón operacional del servicio } s \\[2mm]
g_t^{adm} &: \text{Gastos administrativos en } t \\
RRHH_t &: \text{Costo de recursos humanos en } t \\
VC &: \text{Capital de trabajo inicial} \\
B_t^{min} &: \text{Caja mínima requerida en } t \\
\beta &: \text{Tasa de descuento mensual}
\end{align*}

### Variables de decisión

\begin{align*}
A_{s,t} &\geq 0: \text{Clientes nuevos adquiridos del servicio } s \text{ en } t \\
C_{s,t} &\geq 0: \text{Clientes activos totales del servicio } s \text{ en } t \\
R_{s,t} &\geq 0: \text{Ventas recurrentes del servicio } s \text{ en } t \\
Q_{s,t} &\geq 0: \text{Servicios totales vendidos del servicio } s \text{ en } t \\[2mm]
V_t &\in \mathbb{Z}_+: \text{Vendedores activos en } t \\
L_t &\in \mathbb{Z}_+: \text{Líderes comerciales activos en } t \\
m_{s,t}^{op} &\in \mathbb{Z}_+: \text{Escalón operacional activo del servicio } s \text{ en } t \\[2mm]
Costo_{s,t}^{op} &\geq 0: \text{Costo operacional del servicio } s \text{ en } t \\
Costo_t^{op} &\geq 0: \text{Costo operacional total en } t \\
CAC_t &\geq 0: \text{Costo de adquisición de clientes en } t \\
I_t &\geq 0: \text{Ingresos totales en } t \\
EBITDA_t &\in \mathbb{R}: \text{Resultado operacional en } t \\
Caja_t &\in \mathbb{R}: \text{Caja acumulada al cierre de } t
\end{align*}

### Función objetivo

\begin{align*}
\max \; z = \sum_{t \in T} \frac{EBITDA_t}{(1+\beta)^t}
\end{align*}

### Restricciones

**Adquisición base**

\begin{align*}
A_{s,t} = A_{s,t}^{base}
\quad \forall s \in S,\; t \in T^{base}
\end{align*}

**Stock activo de clientes**

\begin{align*}
C_{s,t} = \sum_{\tau \leq t} \phi_{s,\tau,t} \cdot A_{s,\tau}
\quad \forall s \in S,\; t \in T
\end{align*}

**Ventas recurrentes**

\begin{align*}
R_{s,t} = \sum_{\tau < t} \delta_{s,\tau,t} \cdot \phi_{s,\tau,t} \cdot \alpha_{s,t} \cdot A_{s,\tau}
\quad \forall s \in S,\; t \in T
\end{align*}

**Servicios totales vendidos**

\begin{align*}
Q_{s,t} = A_{s,t} + R_{s,t}
\quad \forall s \in S,\; t \in T
\end{align*}

**Ingresos totales**

\begin{align*}
I_t = \sum_{s \in S} Q_{s,t} \cdot Ticket_s
\quad \forall t \in T
\end{align*}

**Capacidad comercial**

\begin{align*}
\sum_{s \in S} A_{s,t} \leq meta \cdot V_t
\quad \forall t \in T
\end{align*}

Opcionalmente, para evitar adquisición instantánea por vendedores contratados en el mismo período:

\begin{align*}
\sum_{s \in S} A_{s,t} \leq meta \cdot V_{t-1}
\quad \forall t \in T,\; t>1
\end{align*}

**Supervisión comercial**

\begin{align*}
V_t \leq sup \cdot L_t
\quad \forall t \in T
\end{align*}

**Monotonicidad de la fuerza comercial**

\begin{align*}
V_t &\geq V_{t-1} \quad \forall t \in T,\; t>1 \\
L_t &\geq L_{t-1} \quad \forall t \in T,\; t>1
\end{align*}

**Capacidad operacional**

\begin{align*}
Q_{s,t} \leq u_s^{max} m_{s,t}^{op}
\quad \forall s \in S,\; t \in T
\end{align*}

**Costo operacional por servicio**

\begin{align*}
Costo_{s,t}^{op} &\geq c_s^u Q_{s,t}
\quad \forall s \in S,\; t \in T \\
Costo_{s,t}^{op} &\geq c_s^{min} m_{s,t}^{op}
\quad \forall s \in S,\; t \in T
\end{align*}

**Costo operacional total**

\begin{align*}
Costo_t^{op} = \sum_{s \in S} Costo_{s,t}^{op}
\quad \forall t \in T
\end{align*}

**Costo de adquisición**

\begin{align*}
CAC_t =
rem_v V_t
+ rem_l L_t
+ (com_v + com_l)\sum_{s \in S} A_{s,t}Ticket_s
\quad \forall t \in T
\end{align*}

**EBITDA**

\begin{align*}
EBITDA_t =
I_t
- Costo_t^{op}
- CAC_t
- g_t^{adm}
- RRHH_t
\quad \forall t \in T
\end{align*}

**Caja**

\begin{align*}
Caja_0 &= VC \\
Caja_t &= Caja_{t-1} + EBITDA_t
\quad \forall t \in T
\end{align*}

**Restricción de liquidez**

\begin{align*}
Caja_t \geq B_t^{min}
\quad \forall t \in T
\end{align*}

Adicionalmente se presenta un índice para seguir el notebook. Se ejecuta de forma secuencial.

## Estructura del notebook

1. Instalación de librerías
2. Formulación matemática compacta
3. Configuración de parámetros de la instancia  
4. Generación de instancia y preprocesamiento  
5. Implementación del modelo en PuLP/CBC  
6. Revisión de resultados del plan óptimo  
7. Cálculo de valorización por flujos descontados
8. Cálculo de unit economics  
9. Visualizaciones principales  
10. Limitaciones, supuestos y extensiones futuras

## 1. Instalación de solver e importación de librerías
"""

# ================================================================
# Instalación de dependencias
# ================================================================
!pip install pulp --quiet

# ================================================================
# Importación de librerías
# ================================================================
import math
import warnings
from itertools import product as iproduct

import numpy as np
import pandas as pd
import pulp

import matplotlib.pyplot as plt
import matplotlib.ticker as mticker

# ================================================================
# Configuración general
# ================================================================
warnings.filterwarnings("ignore")

pd.set_option("display.float_format", "{:,.2f}".format)
pd.set_option("display.max_columns", 30)
pd.set_option("display.width", 140)

# ================================================================
# Verificación del solver
# ================================================================
print(f"PuLP {pulp.__version__} instalado correctamente")

solver = pulp.PULP_CBC_CMD(msg=False)
print("Solver CBC disponible:", solver is not None)

"""## 2. Configuración de Parámetros


"""

def cargar_parametros_base():
    """
    Define la instancia base del modelo.

    Todos los valores monetarios están expresados en USD.
    La base temporal del modelo es mensual.

    """

    parametros = {

        # ================================================================
        # Horizonte y financiamiento
        # ================================================================
        "H": 36,                         # Horizonte de planificación [meses]
        "VC": 100_000,                   # Capital inicial disponible [USD]
        "beta": 0.35,                    # Tasa de descuento anual ajustada por riesgo

        "g_max_suavizado": 0.25,   # Crecimiento máximo mensual sobre tendencia reciente

        # ================================================================
        # Servicios
        # ================================================================
        # En el MVP se usa un solo servicio, pero la estructura queda preparada
        # para extender el modelo a múltiples servicios.

        "servicios": [
            {
                "nombre": "Servicio",

                # Ingresos
                "ticket": 700,           # Ticket promedio [USD/servicio]

                # Recurrencia y pérdida de clientes
                "frecuencia": 3,         # Recompra cada f meses
                "alpha": 0.9,           # % de clientes elegibles que recompran
                "churn_anual": [0.5, 0.3, 0.15],  # Churn anual por año

                # Costos operacionales
                "c_u": 30,              # Costo unitario por servicio [USD]
                "c_min": 1000,          # Costo mínimo por escalón operacional [USD/mes]
                "u_max": 100,             # Capacidad por escalón operacional [servicios/mes]

                # Adquisición observada o consensuada para los primeros 12 meses
                "A_base": [2, 2, 3, 4, 5, 5, 6, 7, 8, 8, 9, 10],
            },

        ],

        # ================================================================
        # Fuerza comercial
        # ================================================================
        "meta": 8,                       # Clientes nuevos por vendedor al mes
        "sup": 3,                        # Vendedores supervisados por cada líder
        "rem_v": 1_200,                  # Remuneración mensual vendedor [USD]
        "rem_l": 1_700,                  # Remuneración mensual líder [USD]
        "com_v": 0.10,                   # Comisión vendedor sobre nuevas ventas
        "com_l": 0.05,                   # Comisión líder sobre nuevas ventas

        # ================================================================
        # Gastos fijos y estructura
        # ================================================================
        "g_adm": 1_500,                  # Gasto administrativo mensual [USD]

        # Costos de planilla de RRHH por año, expresados como gasto mensual
        "RRHH_mensual": [10_000, 15_000, 20_000],

        # ================================================================
        # Capital de trabajo mínimo
        # ================================================================
        "ciclo_op": [180, 90, 30],       # Ciclo operacional por año [días]
        "buffer_caja": 0,            # Caja adicional mínima [USD]

        # ================================================================
        # Postprocesamiento financiero
        # ================================================================
        "tax": 0.125,                    # Tasa de impuesto a la renta actual en Chile
    }

    return parametros

"""## 3. Generador de Instancia y Preprocesamiento

"""

def generar_instancia(parametros):

    """
    Construye la instancia del modelo a partir de los parámetros brutos. Retorna un diccionario de instancia.

    Preprocesa:
    - churn mensual por servicio y período
    - supervivencia acumulada por cohorte: phi[s,tau,t]
    - indicador binario de recompra: delta[s,tau,t]
    - % de recompra de cohorte tau para servicio en período t: alpha[s,tau,t]
    - adquisición base de los primeros 12 meses
    - costo de planilla de RRHH mensual
    - caja mínima mensual: B_min[t]
    - factor de descuento mensualizado: beta[t]
    """

    H = parametros["H"]

    servicios = parametros["servicios"]
    S = len(servicios)

    beta_anual = parametros["beta"]
    beta_mensual = (1 + beta_anual) ** (1 / 12) - 1

    T = list(range(1, H + 1))
    T_base = list(range(1, 13))

    # ================================================================
    # 1. Churn mensual por servicio y período
    # ================================================================
    churn_mensual = {}

    for s, servicio in enumerate(servicios):
        for t in T:
            ano = min((t - 1) // 12, len(servicio["churn_anual"]) - 1)
            churn_anual = servicio["churn_anual"][ano]

            # Conversión equivalente anual -> mensual
            churn_mensual[(s, t)] = 1 - (1 - churn_anual) ** (1 / 12)

    # ================================================================
    # 2. Supervivencia acumulada phi[s,tau,t]
    # φ_{s,τ,t} = ∏_{c=τ+1}^{t} (1 − Churn_{s,c})
    # ================================================================
    phi = {}

    for s in range(S):
        for tau in T:
            phi[(s, tau, tau)] = 1.0
            for t in range(tau + 1, H + 1):
                phi[(s, tau, t)] = phi[(s, tau, t - 1)] * (1 - churn_mensual[(s, t)])



    # ================================================================
    # 3. Indicador de recompra delta[s,tau,t]
    # δ_{s,τ,t} = 1 si t > τ y (t − τ) ≡ 0 (mod f_s)
    # ================================================================
    delta = {}

    for s, servicio in enumerate(servicios):
        frecuencia = servicio["frecuencia"]
        for tau in T:
            for t in T:
                delta[(s, tau, t)] = int(t > tau and (t - tau) % frecuencia == 0)

    # ================================================================
    # 4. Alpha por servicio y período
    # ================================================================

    alpha = {}

    for s, servicio in enumerate(servicios):
        for t in T:
            alpha[(s, t)] = servicio["alpha"]

    # ================================================================
    # 5. Adquisición base primeros 12 meses
    # ================================================================
    A_base = {}

    for s, servicio in enumerate(servicios):
        plan = servicio["A_base"]

        if len(plan) != 12:
            raise ValueError(f"A_base del servicio {s} debe tener exactamente 12 valores.")

        for t in T_base:
            A_base[(s, t)] = float(plan[t - 1])


    # ================================================================
    # 6. RRHH mensual
    # ================================================================

    RRHH = {}

    for t in T:
        ano = min((t - 1) // 12, len(parametros["RRHH_mensual"]) - 1)
        RRHH[t] = parametros["RRHH_mensual"][ano]

    # ================================================================
    # 7. Caja mínima B_min[t]
    # ================================================================

    # MVP: se calcula con burn fijo de referencia para evitar circularidad.
    # No depende de Costo óptimo del solver.
    B_min = {}

    for t in T:
        ano = min((t - 1) // 12, len(parametros["ciclo_op"]) - 1)

        ciclo_dias = parametros["ciclo_op"][ano]

        # Burn mensual de referencia: administración + RRHH + costo mínimo operacional base
        costo_min_op_ref = sum(servicio["c_min"] for servicio in servicios)
        burn_ref_mensual = parametros["g_adm"] + RRHH[t] + costo_min_op_ref

        # Capital de trabajo requerido por ciclo operacional
        # B_min[t] = (ciclo_dias / 30) * burn_ref_mensual + parametros["buffer_caja"]
        B_min[t] = 0


    # ================================================================
    # 8. Factor de descuento mensual
    # ============================================================

    descuento = {t: 1 / (1 + beta_mensual) ** t for t in T}

    instancia = {
        "H": H,
        "T": T,
        "S": S,
        "servicios": servicios,
        "beta": beta_mensual,
        "beta_anual": beta_anual,
        "descuento": descuento,
        "churn_mensual": churn_mensual,
        "phi": phi,
        "delta": delta,
        "alpha": alpha,
        "T_base": T_base,
        "A_base": A_base,
        "ciclo_op": parametros["ciclo_op"],
        "RRHH": RRHH,
        "B_min": B_min,
        "VC": parametros["VC"],
        "g_adm": parametros["g_adm"],
        "meta": parametros["meta"],
        "sup": parametros["sup"],
        "rem_v": parametros["rem_v"],
        "rem_l": parametros["rem_l"],
        "com_v": parametros["com_v"],
        "com_l": parametros["com_l"],
        "tax": parametros["tax"],
        "parametros": parametros,
        "g_max_suavizado": parametros["g_max_suavizado"],
    }

    return instancia



def mostrar_resumen_instancia(inst):
    """
    Muestra una auditoría básica de la instancia antes de resolver el modelo.
    Sirve para detectar errores de escala, recurrencia, churn, caja mínima
    y coherencia de parámetros.
    """

    H = inst["H"]
    S = inst["S"]

    print("\n" + "═" * 80)
    print("  RESUMEN DE INSTANCIA GENERADA")
    print("═" * 80)

    print(f"Horizonte                       : {H} meses")
    print(f"Servicios                       : {S}")
    print(f"Capital inicial VC              : USD {inst['VC']:,.0f}")
    print(f"Tasa descuento anual             : {inst['beta_anual']*100:.2f}%")
    print(f"Tasa descuento mensual           : {inst['beta']*100:.3f}%")
    print(f"Períodos con adquisición fija     : {inst['T_base'][0]} a {inst['T_base'][-1]}")
    print(f"Gasto administrativo mensual      : USD {inst['g_adm']:,.0f}")
    print(f"Meta por vendedor                 : {inst['meta']} clientes/mes")
    print(f"Supervisión                       : {inst['sup']} vendedores por líder")
    print()

    print("─" * 80)
    print("SERVICIOS")
    print("─" * 80)

    for s, servicio in enumerate(inst["servicios"]):
        A_base_total = sum(servicio["A_base"])
        margen_unitario = servicio["ticket"] - servicio["c_u"]
        gross_margin = margen_unitario / servicio["ticket"] if servicio["ticket"] > 0 else 0

        print(f"\nServicio {s}: {servicio['nombre']}")
        print(f"  Ticket promedio                 : USD {servicio['ticket']:,.0f}")
        print(f"  Costo unitario                  : USD {servicio['c_u']:,.0f}")
        print(f"  Gross margin aproximado          : {gross_margin*100:.1f}%")
        print(f"  Frecuencia recompra              : cada {servicio['frecuencia']} meses")
        print(f"  Alpha recompra                   : {servicio['alpha']*100:.1f}%")
        print(f"  Churn anual                      : {servicio['churn_anual']}")
        print(f"  Churn mensual año 1              : {inst['churn_mensual'][(s,1)]*100:.2f}%")
        print(f"  Capacidad por escalón            : {servicio['u_max']} servicios/mes")
        print(f"  Costo mínimo operacional         : USD {servicio['c_min']:,.0f}/mes")
        print(f"  Plan base 12 meses               : {servicio['A_base']}")
        print(f"  Total adquisición base año 1     : {A_base_total:,.0f} clientes")

        # Supervivencia de la primera cohorte
        periodos_check = [1, 3, 6, 12, 18, 24, 36]
        supervivencia = {
            t: round(inst["phi"].get((s, 1, t), 0), 4)
            for t in periodos_check
            if t <= H
        }
        print(f"  Supervivencia cohorte mes 1      : {supervivencia}")

        # Eventos de recompra de cohorte 1
        eventos_recompra = [
            t for t in range(2, H + 1)
            if inst["delta"].get((s, 1, t), 0) == 1
        ]
        print(f"  Recompras cohorte mes 1          : {eventos_recompra[:12]}")

    """
    print("\n" + "─" * 80)
    print("CAJA MÍNIMA Y RRHH")
    print("─" * 80)

    df_bmin = pd.DataFrame({
        "Mes": list(range(1, 13)),
        "RRHH": [inst["RRHH"][t] for t in range(1, 13)],
        "B_min": [inst["B_min"][t] for t in range(1, 13)],
    })

    print(df_bmin.to_string(index=False))

    print("\n" + "─" * 80)
    print("AUDITORÍA RÁPIDA")
    print("─" * 80)

    advertencias = []

    # 1. Churn
    for s, servicio in enumerate(inst["servicios"]):
        if any(ch < 0 or ch > 1 for ch in servicio["churn_anual"]):
            advertencias.append(f"Servicio {s}: churn anual fuera de rango [0,1].")

    # 2. Alpha
    for s, servicio in enumerate(inst["servicios"]):
        if servicio["alpha"] < 0 or servicio["alpha"] > 1:
            advertencias.append(f"Servicio {s}: alpha fuera de rango [0,1].")

    # 3. Gross margin
    for s, servicio in enumerate(inst["servicios"]):
        gm = (servicio["ticket"] - servicio["c_u"]) / servicio["ticket"]
        if gm < 0.5:
            advertencias.append(f"Servicio {s}: gross margin bajo para startup ({gm*100:.1f}%).")
        if gm > 0.95:
            advertencias.append(f"Servicio {s}: gross margin muy alto; revisar costo unitario.")

    # 4. Caja mínima vs VC
    bmin_max = max(inst["B_min"].values())
    if bmin_max > inst["VC"]:
        advertencias.append(
            f"B_min máximo (USD {bmin_max:,.0f}) supera el VC inicial. "
            "Alta probabilidad de infactibilidad."
        )

    # 5. Plan base vs capacidad comercial mínima
    total_A_base_mes = {
        t: sum(inst["A_base"][(s, t)] for s in range(S))
        for t in inst["T_base"]
    }
    max_A_base = max(total_A_base_mes.values())
    vendedores_minimos = math.ceil(max_A_base / inst["meta"])

    print(f"Máxima adquisición mensual base    : {max_A_base:,.0f} clientes")
    print(f"Vendedores mínimos para plan base  : {vendedores_minimos}")
    print(f"B_min máximo                       : USD {bmin_max:,.0f}")
    print(f"B_min mes 1                        : USD {inst['B_min'][1]:,.0f}")

    if advertencias:
        print("\nAdvertencias:")
        for adv in advertencias:
            print(f" {adv}")
    else:
        print("\nSin advertencias críticas en preprocesamiento.")

    print("═" * 80)
    """



parametros = cargar_parametros_base()
instancia = generar_instancia(parametros)
mostrar_resumen_instancia(instancia)

"""## 4. Implementación modelo de optimización"""

def construir_y_resolver_modelo(inst, verbose=False, time_limit=120):
    """
    Construye y resuelve el modelo MILP en PuLP/CBC.

    Modelo base:
    - Adquisición fija en los primeros 12 meses.
    - Adquisición posterior decidida por el solver.
    - Recurrencia por cohortes preprocesada.
    - EBITDA puede ser negativo.
    - Caja acumulada se mantiene como control de liquidez.
    """

    import pulp

    H = inst["H"]
    S = inst["S"]
    T = inst["T"]
    servicios = inst["servicios"]

    print("═" * 80)
    print("  CONSTRUYENDO MODELO MILP — OPTIMIZACION PCA")
    print("═" * 80)

    # ================================================================
    # Crear problema
    # ================================================================
    prob = pulp.LpProblem("optimizacion_pca", pulp.LpMaximize)

    # ================================================================
    # VARIABLES
    # ================================================================

    # -----------------------------
    # Variables de decisión
    # -----------------------------

    # A_{s,t} ≥ 0: nuevos clientes adquiridos
    A = {(s, t): pulp.LpVariable(f"A_{s}_{t}", lowBound=0)
         for s in range(S) for t in T}

    # V_t ∈ Z+: vendedores activos
    V = {t: pulp.LpVariable(f"V_{t}", lowBound=0, cat="Integer")
         for t in T}

    # L_t ∈ Z+: líderes comerciales
    L = {t: pulp.LpVariable(f"L_{t}", lowBound=0, cat="Integer")
         for t in T}

    # m_op_{s,t} ∈ Z+: escalones operacionales
    m_op = {(s, t): pulp.LpVariable(f"m_op_{s}_{t}", lowBound=0, cat="Integer")
            for s in range(S) for t in T}

    # -----------------------------
    # Variables de estado
    # -----------------------------

    # C_{s,t} ≥ 0: clientes activos
    C = {(s, t): pulp.LpVariable(f"C_{s}_{t}", lowBound=0)
         for s in range(S) for t in T}

    # Caja_t libre: liquidez acumulada
    Caja = {t: pulp.LpVariable(f"Caja_{t}", lowBound=None)
            for t in T}

    # -----------------------------
    # Variables auxiliares
    # -----------------------------

    # R_{s,t} ≥ 0: ventas recurrentes
    R = {(s, t): pulp.LpVariable(f"R_{s}_{t}", lowBound=0)
         for s in range(S) for t in T}

    # Q_{s,t} ≥ 0: servicios vendidos
    Q = {(s, t): pulp.LpVariable(f"Q_{s}_{t}", lowBound=0)
         for s in range(S) for t in T}

    # I_{s,t} ≥ 0: ingresos
    I = {(s, t): pulp.LpVariable(f"I_{s}_{t}", lowBound=0)
         for s in range(S) for t in T}

    # Cost_op_{s,t} ≥ 0: costo operacional
    Cost_op = {(s, t): pulp.LpVariable(f"Cost_op_{s}_{t}", lowBound=0)
               for s in range(S) for t in T}

    # CAC_t ≥ 0: costo de adquisición
    CAC = {t: pulp.LpVariable(f"CAC_{t}", lowBound=0)
           for t in T}

    # EBITDA_t libre: resultado operacional
    EBITDA = {t: pulp.LpVariable(f"EBITDA_{t}", lowBound=None)
              for t in T}

    # ================================================================
    # FUNCIÓN OBJETIVO
    # ================================================================
    # Max VPL del EBITDA

    prob += pulp.lpSum(
        inst["descuento"][t] * EBITDA[t] for t in T
    ), "FO_VPL_EBITDA"

    # ================================================================
    # RESTRICCIONES
    # ================================================================

    # R1: fija adquisición base
    for s in range(S):
        for t in inst["T_base"]:
            prob += A[(s, t)] == inst["A_base"][(s, t)]

    # R1b: suavizamiento de adquisición post plan base
    # Evita saltos no plausibles respecto de la trayectoria consensuada.
    # No fija el MoM; solo acota la aceleración máxima admisible.

    g = inst["g_max_suavizado"]

    for s in range(S):

        # Base de transición: mayor entre adquisición mes 12 y promedio últimos 12 meses
        promedio_base = sum(inst["A_base"][(s, t)] for t in inst["T_base"]) / len(inst["T_base"])
        base_transicion = max(inst["A_base"][(s, 12)], promedio_base)

        # Mes 13: transición desde el plan consensuado
        prob += A[(s, 13)] <= (1 + g) * base_transicion

        # Mes 14: transición desde el mes 13
        prob += A[(s, 14)] <= (1 + g) * A[(s, 13)]

        # Meses 15-36: crecimiento suavizado por media móvil de 3 meses
        for t in range(15, H + 1):
            prob += A[(s, t)] <= ((1 + g) / 3) * (
                A[(s, t - 1)] + A[(s, t - 2)] + A[(s, t - 3)]
            )

    # R2: clientes activos por cohorte
    for s in range(S):
        for t in T:
            prob += C[(s, t)] == pulp.lpSum(
                inst["phi"].get((s, tau, t), 0) * A[(s, tau)]
                for tau in range(1, t + 1)
            )

    # R3: ventas recurrentes
    for s in range(S):
        for t in T:
            prob += R[(s, t)] == pulp.lpSum(
                inst["delta"].get((s, tau, t), 0)
                * inst["phi"].get((s, tau, t), 0)
                * inst["alpha"].get((s, t), 0)
                * A[(s, tau)]
                for tau in range(1, t)
            )

    # R4: servicios totales
    for s in range(S):
        for t in T:
            prob += Q[(s, t)] == A[(s, t)] + R[(s, t)]

    # R5: ingresos
    for s in range(S):
        ticket = servicios[s]["ticket"]
        for t in T:
            prob += I[(s, t)] == ticket * Q[(s, t)]
    """
    # R6: capacidad comercial
    for t in T:
        prob += pulp.lpSum(A[(s, t)] for s in range(S)) <= inst["meta"] * V[t]

    # R7: supervisión
    for t in T:
        prob += V[t] <= inst["sup"] * L[t]

    # R8-R9: monotonicidad
    for t in T:
        if t > 1:
            prob += V[t] >= V[t - 1]
            prob += L[t] >= L[t - 1]
    """
    # R6: fuerza comercial para plan base y capacidad comercial post año 1
    # Meses 1-12: la adquisición viene dada; se fija la dotación mínima necesaria.
    # Meses 13-36: la adquisición optimizada queda limitada por capacidad comercial.

    for t in T:
        prob += V[1] >= 1
        prob += L[1] >= 1
        if t <= 12:
            adq_base_t = sum(inst["A_base"][(s, t)] for s in range(S))

            vendedores_base_t = math.ceil(adq_base_t / inst["meta"])
            lideres_base_t = math.ceil(vendedores_base_t / inst["sup"])

            prob += V[t] == vendedores_base_t
            prob += L[t] == lideres_base_t

        else:
            prob += pulp.lpSum(A[(s, t)] for s in range(S)) <= inst["meta"] * V[t]
            prob += V[t] <= inst["sup"] * L[t]

    # R7: monotonicidad comercial desde el mes 13
    # Evita contratar y despedir artificialmente durante el período optimizado.
    for t in T:
        prob += V[1] >= 1
        prob += L[1] >= 1
        if t > 13:
            prob += V[t] >= V[t - 1]
            prob += L[t] >= L[t - 1]


    # R10: capacidad operacional
    for s in range(S):
        u_max = servicios[s]["u_max"]
        for t in T:
            prob += Q[(s, t)] <= u_max * m_op[(s, t)]

    # R11: costo variable
    for s in range(S):
        c_u = servicios[s]["c_u"]
        for t in T:
            prob += Cost_op[(s, t)] >= c_u * Q[(s, t)]

    # R12: costo mínimo escalón
    for s in range(S):
        c_min = servicios[s]["c_min"]
        for t in T:
            prob += Cost_op[(s, t)] >= c_min * m_op[(s, t)]

    # R13: CAC
    for t in T:
        prob += CAC[t] == (
            inst["rem_v"] * V[t]
            + inst["rem_l"] * L[t]
            + pulp.lpSum(
                (inst["com_v"] + inst["com_l"])
                * servicios[s]["ticket"]
                * A[(s, t)]
                for s in range(S)
            )
        )

    # R14: EBITDA
    for t in T:
        prob += EBITDA[t] == (
            pulp.lpSum(I[(s, t)] for s in range(S))
            - pulp.lpSum(Cost_op[(s, t)] for s in range(S))
            - CAC[t]
            - inst["g_adm"]
            - inst["RRHH"][t]
        )

    # R15: balance de caja
    prob += Caja[1] == inst["VC"] + EBITDA[1]

    for t in T:
        if t > 1:
            prob += Caja[t] == Caja[t - 1] + EBITDA[t]


    # R16: caja mínima (en MVP puede ser 0)
    #for t in T:
     #   prob += Caja[t] >= 0

    """
    runway_meses = 2

    for t in T:
        gastos_fijos = inst["RRHH"][t] + inst["g_adm"]
        prob += Caja[t] >= - runway_meses * gastos_fijos




    # R16: Caja ≥ capital de trabajo dinámico

    for t in T:
        # identificar año
        ano = min((t - 1) // 12, len(inst["ciclo_op"]) - 1)
        ciclo_dias = inst["ciclo_op"][ano]

        # aproximación lineal del burn mensual
        egresos = (
            pulp.lpSum(Cost_op[(s, t)] for s in range(S))
            + CAC[t]
            + inst["g_adm"]
            + inst["RRHH"][t]
        )

        # capital de trabajo requerido
        kt_req = (ciclo_dias / 30.0) * egresos
        prob += Caja[t] >= kt_req
    """

    # ================================================================
    # REPORTE
    # ================================================================

    print(f"Variables totales      : {len(prob.variables())}")
    print(f"Restricciones          : {len(prob.constraints)}")

    # ================================================================
    # SOLVER
    # ================================================================

    print("Resolviendo...")
    solver = pulp.PULP_CBC_CMD(msg=1 if verbose else 0, timeLimit=time_limit)
    prob.solve(solver)

    status = pulp.LpStatus[prob.status]
    obj = pulp.value(prob.objective)

    print(f"Status                : {status}")
    if obj:
        print(f"VPL EBITDA            : {obj:,.2f}")

    print("═" * 80)

    return status, prob, {
        "A": A, "C": C, "R": R, "Q": Q, "I": I,
        "V": V, "L": L, "m_op": m_op,
        "Cost_op": Cost_op, "CAC": CAC,
        "EBITDA": EBITDA, "Caja": Caja
    }


status, prob, variables = construir_y_resolver_modelo(
    instancia,
    verbose=False,
    time_limit=120
)

"""## 5. Generación del plan de crecimiento acelerado óptimo

"""

def extraer_resultados(inst, vars_dict):
    """
    Extrae los resultados del modelo optimizado y construye un DataFrame mensual.

    El DataFrame conserva la lógica metodológica:
    clientes → servicios → ingresos → costos → EBITDA → caja.
    """

    H = inst["H"]
    S = inst["S"]
    T = inst["T"]
    servicios = inst["servicios"]

    def valor(variable):
        """Extrae valor numérico de una variable PuLP."""
        x = pulp.value(variable)
        return 0.0 if x is None else x

    filas = []

    for t in T:
        anio = (t - 1) // 12 + 1
        mes_anio = (t - 1) % 12 + 1

        fila = {
            "t": t,
            "Año": anio,
            "Mes": mes_anio,

            # Estructura comercial
            "Vendedores": valor(vars_dict["V"][t]),
            "Lideres": valor(vars_dict["L"][t]),

            # Resultados financieros agregados
            "CAC": valor(vars_dict["CAC"][t]),
            "EBITDA": valor(vars_dict["EBITDA"][t]),
            "Caja": valor(vars_dict["Caja"][t]),
            "RRHH": inst["RRHH"][t],
            "G_adm": inst["g_adm"],
        }

        for s in range(S):
            nombre = servicios[s]["nombre"]

            fila[f"A_{nombre}"] = valor(vars_dict["A"][(s, t)])
            fila[f"C_{nombre}"] = valor(vars_dict["C"][(s, t)])
            fila[f"R_{nombre}"] = valor(vars_dict["R"][(s, t)])
            fila[f"Q_{nombre}"] = valor(vars_dict["Q"][(s, t)])
            fila[f"I_{nombre}"] = valor(vars_dict["I"][(s, t)])
            fila[f"Cost_op_{nombre}"] = valor(vars_dict["Cost_op"][(s, t)])
            fila[f"m_op_{nombre}"] = valor(vars_dict["m_op"][(s, t)])

        filas.append(fila)

    df = pd.DataFrame(filas)

    nombres = [srv["nombre"] for srv in servicios]

    df["Adq_clientes"] = df[[f"A_{n}" for n in nombres]].sum(axis=1)
    df["Clientes_activos"] = df[[f"C_{n}" for n in nombres]].sum(axis=1)
    df["Ventas_recurrentes"] = df[[f"R_{n}" for n in nombres]].sum(axis=1)
    df["Servicios_totales"] = df[[f"Q_{n}" for n in nombres]].sum(axis=1)
    df["Ingresos"] = df[[f"I_{n}" for n in nombres]].sum(axis=1)
    df["Costo_operacional"] = df[[f"Cost_op_{n}" for n in nombres]].sum(axis=1)

    df["Costos_totales_sin_CAC"] = df["Costo_operacional"] + df["G_adm"] + df["RRHH"]
    df["Egresos_totales"] = df["Costo_operacional"] + df["CAC"] + df["G_adm"] + df["RRHH"]
    df["EBITDA_acum"] = df["EBITDA"].cumsum()

    df["MoM_adq"] = df["Adq_clientes"].pct_change().replace([np.inf, -np.inf], np.nan)
    df["MoM_ingresos"] = df["Ingresos"].pct_change().replace([np.inf, -np.inf], np.nan)

    df["Ingresos_recurrentes_proxy"] = 0.0
    for s, srv in enumerate(servicios):
        nombre = srv["nombre"]
        df["Ingresos_recurrentes_proxy"] += df[f"R_{nombre}"] * srv["ticket"]

    df["ARR_pct"] = np.where(
        df["Ingresos"] > 0,
        df["Ingresos_recurrentes_proxy"] / df["Ingresos"],
        0
    )

    return df


def imprimir_resultados_mvp(df, inst):
    """
    Imprime resultados principales del plan optimizado en formato MVP.

    Incluye:
    1. Resumen ejecutivo.
    2. Resumen anual.
    3. Plan mensual de clientes, servicios e ingresos.
    4. Plan mensual de costos, CAC, EBITDA y caja.
    """

    print("═" * 90)
    print("  RESULTADOS MVP — PLAN DE CRECIMIENTO ACELERADO")
    print("═" * 90)

    # ================================================================
    # 1. Resumen ejecutivo
    # ================================================================
    ingresos_total = df["Ingresos"].sum()
    ebitda_total = df["EBITDA"].sum()
    caja_final = df["Caja"].iloc[-1]
    caja_min = df["Caja"].min()
    mes_caja_min = int(df.loc[df["Caja"].idxmin(), "t"])
    clientes_final = df["Clientes_activos"].iloc[-1]
    adq_total = df["Adq_clientes"].sum()

    print("\nRESUMEN EJECUTIVO")
    print("-" * 90)
    print(f"Capital inicial VC              : USD {inst['VC']:,.0f}")
    print(f"Clientes adquiridos totales      : {adq_total:,.0f}")
    print(f"Clientes activos mes 36          : {clientes_final:,.0f}")
    print(f"Ingresos acumulados              : USD {ingresos_total:,.0f}")
    print(f"EBITDA acumulado                 : USD {ebitda_total:,.0f}")
    print(f"Caja final                       : USD {caja_final:,.0f}")
    print(f"Caja mínima observada            : USD {caja_min:,.0f} en mes {mes_caja_min}")
    print(f"Vendedores máximos               : {df['Vendedores'].max():,.0f}")
    print(f"Líderes máximos                  : {df['Lideres'].max():,.0f}")

    # ================================================================
    # 2. Resumen anual
    # ================================================================
    resumen_anual = df.groupby("Año").agg({
        "Adq_clientes": "sum",
        "Clientes_activos": "last",
        "Ventas_recurrentes": "sum",
        "Servicios_totales": "sum",
        "Ingresos": "sum",
        "Costo_operacional": "sum",
        "CAC": "sum",
        "G_adm": "sum",
        "RRHH": "sum",
        "EBITDA": "sum",
        "Caja": "last",
        "Vendedores": "max",
        "Lideres": "max",
        "ARR_pct": "mean",
    })

    resumen_anual = resumen_anual.rename(columns={
        "Adq_clientes": "Adq. clientes",
        "Clientes_activos": "Clientes activos fin",
        "Ventas_recurrentes": "Ventas recurrentes",
        "Servicios_totales": "Servicios totales",
        "Ingresos": "Ingresos USD",
        "Costo_operacional": "Costo op.",
        "CAC": "CAC",
        "G_adm": "G. adm.",
        "RRHH": "RRHH",
        "EBITDA": "EBITDA",
        "Caja": "Caja fin año",
        "Vendedores": "Vend. max",
        "Lideres": "Líderes max",
        "ARR_pct": "ARR promedio",
    })

    resumen_anual["ARR promedio"] = resumen_anual["ARR promedio"] * 100

    print("\nRESUMEN ANUAL")
    print("-" * 90)
    print(resumen_anual.round(1).to_string())

    # ================================================================
    # 3. Plan mensual: clientes, servicios e ingresos
    # ================================================================
    plan_comercial = df[[
        "t", "Año", "Mes",
        "Adq_clientes",
        "Clientes_activos",
        "Ventas_recurrentes",
        "Servicios_totales",
        "Ingresos",
        "ARR_pct",
        "Vendedores",
        "Lideres",
    ]].copy()

    plan_comercial["ARR_pct"] = plan_comercial["ARR_pct"] * 100

    plan_comercial = plan_comercial.rename(columns={
        "Adq_clientes": "Adq.",
        "Clientes_activos": "Clientes",
        "Ventas_recurrentes": "Recurrentes",
        "Servicios_totales": "Servicios",
        "Ingresos": "Ingresos",
        "ARR_pct": "ARR %",
        "Vendedores": "Vend.",
        "Lideres": "Lid.",
    })

    print("\nPLAN MENSUAL — CLIENTES, SERVICIOS E INGRESOS")
    print("-" * 90)
    print(plan_comercial.round(1).to_string(index=False))

    # ================================================================
    # 4. Plan mensual: costos, CAC, EBITDA y caja
    # ================================================================
    plan_financiero = df[[
        "t", "Año", "Mes",
        "Costo_operacional",
        "CAC",
        "G_adm",
        "RRHH",
        "Egresos_totales",
        "EBITDA",
        "EBITDA_acum",
        "Caja",
    ]].copy()

    plan_financiero = plan_financiero.rename(columns={
        "Costo_operacional": "Costo op.",
        "G_adm": "G. adm.",
        "Egresos_totales": "Egresos",
        "EBITDA_acum": "EBITDA acum.",
    })

    print("\nPLAN MENSUAL — COSTOS, CAC, EBITDA Y CAJA")
    print("-" * 90)
    print(plan_financiero.round(0).to_string(index=False))


df_resultados = extraer_resultados(instancia, variables)
imprimir_resultados_mvp(df_resultados, instancia)

"""## 6. Valorización por DCF

"""

def calcular_valorizacion_dcf(df, inst):
    """
    Valorización estándar mediante DCF.

    Lógica:
    - Capital de trabajo inicial = VC.
    - Flujo mensual antes de impuestos = EBITDA.
    - Impuesto solo si EBITDA > 0.
    - Flujo neto = EBITDA - impuesto.
    - Valor de desecho = EBITDA último mes anualizado * multiplicador.
    - VAN = -VC + VP(flujos mensuales) + VP(valor de desecho).

    Retorna:
    - DataFrame mensual de flujo de caja.
    - Resumen anual.
    - Métricas principales del DCF.
    """

    H = inst["H"]
    beta_mensual = inst["beta"]
    beta_anual = inst["beta_anual"]
    VC = inst["VC"]

    parametros = inst.get("parametros", inst.get("params", {}))
    tax = parametros.get("tax", 0.125)
    mult_vd_ebitda = parametros.get("mult_vd_ebitda", 1.0)

    print("═" * 80)
    print("  VALORIZACIÓN POR FLUJO DE CAJA DESCONTADO (DCF)")
    print("═" * 80)
    print(f"Capital de trabajo inicial : USD {VC:,.0f}")
    print(f"Tasa descuento anual       : {beta_anual*100:.2f}%")
    print(f"Tasa descuento mensual     : {beta_mensual*100:.3f}%")
    print(f"Tasa impuesto              : {tax*100:.1f}%")
    print(f"Multiplicador VD EBITDA    : {mult_vd_ebitda:.2f}x")
    print()

    # ================================================================
    # DataFrame mensual de flujo de caja
    # ================================================================

    fc = pd.DataFrame({
        "t": df["t"],
        "Año": df["Año"],
        "Ingresos": df["Ingresos"],
        "Costo_operacional": df["Costo_operacional"],
        "CAC": df["CAC"],
        "G_adm": df["G_adm"],
        "RRHH": df["RRHH"],
        "EBITDA": df["EBITDA"],
    })

    fc["Impuesto"] = fc["EBITDA"].apply(lambda x: max(x * tax, 0))
    fc["FC_neto"] = fc["EBITDA"] - fc["Impuesto"]
    fc["Factor_desc"] = 1 / (1 + beta_mensual) ** fc["t"]
    fc["FC_desc"] = fc["FC_neto"] * fc["Factor_desc"]

    # ================================================================
    # Valor de desecho
    # ================================================================

    ebitda_ultimo_mes = fc.iloc[-1]["EBITDA"]
    ebitda_anualizado = ebitda_ultimo_mes * 12

    valor_desecho_nominal = max(ebitda_anualizado * mult_vd_ebitda, 0)
    factor_desc_H = 1 / (1 + beta_mensual) ** H
    valor_desecho_vp = valor_desecho_nominal * factor_desc_H

    # ================================================================
    # VAN
    # ================================================================

    vp_flujos = fc["FC_desc"].sum()
    VAN = -VC + vp_flujos + valor_desecho_vp

    # ================================================================
    # Resumen anual
    # ================================================================

    resumen_anual = fc.groupby("Año").agg({
        "Ingresos": "sum",
        "Costo_operacional": "sum",
        "CAC": "sum",
        "G_adm": "sum",
        "RRHH": "sum",
        "EBITDA": "sum",
        "Impuesto": "sum",
        "FC_neto": "sum",
        "FC_desc": "sum",
    })

    print("RESUMEN ANUAL DCF")
    print("-" * 80)
    print(resumen_anual.round(0).to_string())

    print("\nRESULTADOS DCF")
    print("-" * 80)
    print(f"VP flujos operacionales   : USD {vp_flujos:,.0f}")
    print(f"EBITDA último mes         : USD {ebitda_ultimo_mes:,.0f}")
    print(f"EBITDA anualizado         : USD {ebitda_anualizado:,.0f}")
    print(f"Valor de desecho nominal  : USD {valor_desecho_nominal:,.0f}")
    print(f"Valor de desecho VP       : USD {valor_desecho_vp:,.0f}")
    print(f"Capital trabajo inicial   : USD {-VC:,.0f}")
    print("-" * 80)
    print(f"VAN                       : USD {VAN:,.0f}")
    print("═" * 80)

    return {
        "df_flujo_caja": fc,
        "resumen_anual_dcf": resumen_anual,
        "vp_flujos": vp_flujos,
        "valor_desecho_nominal": valor_desecho_nominal,
        "valor_desecho_vp": valor_desecho_vp,
        "VAN": VAN,
    }


def calcular_valorizacion_multiplos(df, inst):
    """
    Valorización básica mediante múltiplos.

    Lógica:
    - Se toma el último año del horizonte como año de referencia.
    - Se calcula valorización por múltiplo de ingresos.
    - Se calcula valorización por múltiplo de EBITDA.
    """

    parametros = inst.get("parametros", inst.get("params", {}))

    mult_ingresos = parametros.get("mult_ingresos", 1.5)
    mult_ebitda = parametros.get("mult_ebitda", 3.0)

    ultimo_anio = int(df["Año"].max())
    df_ref = df[df["Año"] == ultimo_anio].copy()

    ingresos_anual = df_ref["Ingresos"].sum()
    ebitda_anual = df_ref["EBITDA"].sum()

    valor_por_ingresos = ingresos_anual * mult_ingresos
    valor_por_ebitda = max(ebitda_anual, 0) * mult_ebitda

    resumen_multiplos = pd.DataFrame([
        {
            "Método": "Múltiplo de ingresos",
            "Base": ingresos_anual,
            "Múltiplo": mult_ingresos,
            "Valorización": valor_por_ingresos,
        },
        {
            "Método": "Múltiplo de EBITDA",
            "Base": ebitda_anual,
            "Múltiplo": mult_ebitda,
            "Valorización": valor_por_ebitda,
        },
    ])

    print("═" * 80)
    print("  VALORIZACIÓN POR MÚLTIPLOS")
    print("═" * 80)
    print(f"Año de referencia        : Año {ultimo_anio}")
    print(f"Ingresos año referencia  : USD {ingresos_anual:,.0f}")
    print(f"EBITDA año referencia    : USD {ebitda_anual:,.0f}")
    print()

    print("RESUMEN POR MÚLTIPLOS")
    print("-" * 80)
    print(resumen_multiplos.round(0).to_string(index=False))

    print("═" * 80)

    return {
        "df_multiplos": resumen_multiplos,
        "valor_por_ingresos": valor_por_ingresos,
        "valor_por_ebitda": valor_por_ebitda,
    }


# ================================================================
# Ejecución
# ================================================================

resultados_dcf = calcular_valorizacion_dcf(df_resultados, instancia)
df_flujo_caja = resultados_dcf["df_flujo_caja"]

print()

resultados_multiplos = calcular_valorizacion_multiplos(df_resultados, instancia)
df_multiplos = resultados_multiplos["df_multiplos"]

"""## 7. Unit Economics

"""

def calcular_unit_economics(df, inst, resultados_dcf=None):
    """
    Calcula Unit Economics completos del plan de crecimiento.

    Incluye las métricas usadas en el anexo:
    adquisición, MoM, churn, CAC, ticket, recurrencia, ARR, GP,
    ARPU, cash burn rate, bootstrapping, LTV, LTV(2), LTV/CAC
    y clientes monetizados.
    """

    servicios = inst["servicios"]
    parametros = inst.get("parametros", inst.get("params", {}))

    beta_anual = inst["beta_anual"]
    VC = inst["VC"]

    total_adq = df["Adq_clientes"].sum()
    total_ingresos = df["Ingresos"].sum()
    total_cost_op = df["Costo_operacional"].sum()
    total_cac = df["CAC"].sum()
    total_ebitda_negativo = -df.loc[df["EBITDA"] < 0, "EBITDA"].sum()

    ticket_prom = np.mean([s["ticket"] for s in servicios])
    frecuencia_prom = np.mean([s["frecuencia"] for s in servicios])
    recurrencia_mensual = 1 / frecuencia_prom if frecuencia_prom > 0 else 0
    recurrencia_anual = 12 / frecuencia_prom if frecuencia_prom > 0 else 0

    churn_anual = np.mean([s["churn_anual"][0] for s in servicios])

    cac_prom = total_cac / total_adq if total_adq > 0 else 0

    ingresos_recurrentes = df["Ingresos_recurrentes_proxy"].sum() if "Ingresos_recurrentes_proxy" in df.columns else 0
    arr_pct = ingresos_recurrentes / total_ingresos if total_ingresos > 0 else 0

    gp = 1 - (total_cost_op / total_ingresos) if total_ingresos > 0 else 0

    # arpu = (ticket_prom * arr_pct * gp) - cac_prom
    clientes_activos_prom = df["Clientes_activos"].mean()
    arpu = (total_ingresos / (clientes_activos_prom * len(df))) if clientes_activos_prom > 0 else 0

    cbr_diario = total_ebitda_negativo / 360

    ciclo_op = parametros.get("ciclo_op", [30])[0]
    ct_base_ue = cbr_diario * ciclo_op
    bootstrapping = max(VC, ct_base_ue)

    churn_m_a1 = 1 - (1 - servicios[0]["churn_anual"][0]) ** (1/12)
    gp_marginal = 1 - servicios[0]["c_u"] / servicios[0]["ticket"]
    ltv = (ticket_prom * gp_marginal) / churn_m_a1

    van = resultados_dcf["VAN"] if resultados_dcf is not None and "VAN" in resultados_dcf else np.nan
    ltv_2 = van / total_adq if total_adq > 0 and not pd.isna(van) else np.nan

    ltv_cac = ltv / cac_prom if cac_prom > 0 else 0

    clientes_monetizados = total_adq * arr_pct

    adq_anio_1 = df[df["Año"] == 1]["Adq_clientes"].sum()
    base_adq = df[df["Año"] == 1]["Adq_clientes"].iloc[0] if len(df[df["Año"] == 1]) > 0 else np.nan
    mom_growth = ((adq_anio_1 / base_adq) ** (1 / 11) - 1) if base_adq and base_adq > 0 else np.nan

    df_units = pd.DataFrame([
        {
            "Unit Economic": "Adquisición",
            "Definición": "Clientes nuevos captados en el horizonte",
            "Fórmula / Fuente": "Σ Adquisición mensual",
            "Valor": total_adq,
            "Unidad": "# clientes",
        },
        {
            "Unit Economic": "MoM Growth",
            "Definición": "Crecimiento mensual equivalente de adquisición",
            "Fórmula / Fuente": "(Σ Adq. año 1 / base)^(1/11) - 1",
            "Valor": mom_growth,
            "Unidad": "%",
        },
        {
            "Unit Economic": "CHURN",
            "Definición": "Porcentaje de clientes perdidos en un año",
            "Fórmula / Fuente": "Parámetro promedio año 1",
            "Valor": churn_anual,
            "Unidad": "%",
        },
        {
            "Unit Economic": "CAC",
            "Definición": "Costo de adquisición por cliente",
            "Fórmula / Fuente": "Σ CAC / Σ Adquisición",
            "Valor": cac_prom,
            "Unidad": "USD/cliente",
        },
        {
            "Unit Economic": "Ticket promedio",
            "Definición": "Precio promedio por servicio",
            "Fórmula / Fuente": "Parámetro configurado",
            "Valor": ticket_prom,
            "Unidad": "USD",
        },
        {
            "Unit Economic": "Recurrencia mensual",
            "Definición": "Veces que compra cada cliente al mes",
            "Fórmula / Fuente": "1 / frecuencia promedio",
            "Valor": recurrencia_mensual,
            "Unidad": "veces/mes",
        },
        {
            "Unit Economic": "ARR",
            "Definición": "Porcentaje de ingresos recurrentes sobre total",
            "Fórmula / Fuente": "Ingresos recurrentes / Total ingresos",
            "Valor": arr_pct,
            "Unidad": "%",
        },
        {
            "Unit Economic": "Gross Profit (GP)",
            "Definición": "Margen bruto operacional",
            "Fórmula / Fuente": "1 - Costos operacionales / Ingresos",
            "Valor": gp,
            "Unidad": "%",
        },
        {
            "Unit Economic": "ARPU",
            "Definición": "Ingreso promedio por usuario",
            "Fórmula / Fuente": "Ingresos totales / clientes activos promedio * horizonte",
            "Valor": arpu,
            "Unidad": "USD/cliente",
        },
        {
            "Unit Economic": "Cash Burn Rate",
            "Definición": "Dinero consumido por día",
            "Fórmula / Fuente": "Σ EBITDA negativo / 360",
            "Valor": cbr_diario,
            "Unidad": "USD/día",
        },
        {
            "Unit Economic": "Bootstrapping",
            "Definición": "Capital de trabajo hasta punto de equilibrio",
            "Fórmula / Fuente": "max(VC, CBR × ciclo operacional)",
            "Valor": bootstrapping,
            "Unidad": "USD",
        },
        {
            "Unit Economic": "LTV",
            "Definición": "Valor total estimado que genera cada cliente",
            "Fórmula / Fuente": "(Ticket × Recurrencia anual) / β",
            "Valor": ltv,
            "Unidad": "USD/cliente",
        },
        {
            "Unit Economic": "LTV(2)",
            "Definición": "Valor por cliente medido por VAN",
            "Fórmula / Fuente": "VAN / Σ adquisición",
            "Valor": ltv_2,
            "Unidad": "USD/cliente",
        },
        {
            "Unit Economic": "LTV/CAC",
            "Definición": "Eficiencia del capital de adquisición",
            "Fórmula / Fuente": "LTV / CAC",
            "Valor": ltv_cac,
            "Unidad": "ratio",
        },
        {
            "Unit Economic": "Clientes monetizados",
            "Definición": "Clientes que compran recurrentemente",
            "Fórmula / Fuente": "Adquisición × ARR",
            "Valor": clientes_monetizados,
            "Unidad": "# clientes",
        },
    ])

    df_print = df_units.copy()

    def formatear_valor(row):
        valor = row["Valor"]
        unidad = row["Unidad"]

        if pd.isna(valor):
            return "N/D"

        if unidad == "%":
            return f"{valor * 100:,.1f}%"
        if unidad in ["USD", "USD/cliente", "USD/día"]:
            return f"USD {valor:,.0f}"
        if unidad == "ratio":
            return f"{valor:,.2f}x"
        if unidad in ["# clientes"]:
            return f"{valor:,.0f}"
        return f"{valor:,.2f}"

    df_print["Valor"] = df_print.apply(formatear_valor, axis=1)

    print("═" * 100)
    print("  UNIT ECONOMICS COMPLETOS")
    print("═" * 100)
    print(df_print.to_string(index=False))
    print("═" * 100)

    return df_units


df_unit_economics = calcular_unit_economics(
    df_resultados,
    instancia,
    resultados_dcf
)

"""## 8. Visualizaciones preliminares

"""

def generar_visualizaciones(df, inst, resultados_dcf=None, df_unit_economics=None, filename="visualizaciones_pca.png"):
    """
    Genera visualizaciones principales del Plan de Crecimiento Acelerado.

    Gráficos:
    1. Clientes activos y adquisición mensual.
    2. Ingresos mensuales.
    3. Costos, CAC y EBITDA.
    4. Caja acumulada.
    5. Servicios nuevos y recurrentes.
    6. Valorización DCF resumida.
    """

    import matplotlib.pyplot as plt
    import matplotlib.ticker as mticker

    fig, axes = plt.subplots(3, 2, figsize=(16, 14))
    axes = axes.flatten()

    def formato_usd(x, pos):
        return f"{x:,.0f}"

    # ============================================================
    # 1. Clientes activos y adquisición
    # ============================================================
    ax = axes[0]
    ax.plot(df["t"], df["Clientes_activos"], linewidth=2, label="Clientes activos")
    ax.bar(df["t"], df["Adq_clientes"], alpha=0.5, label="Adquisición mensual")
    ax.axvline(12.5, linestyle="--", linewidth=1, label="Fin plan base")
    ax.set_title("Clientes activos y adquisición mensual")
    ax.set_xlabel("Mes")
    ax.set_ylabel("Clientes")
    ax.legend()
    ax.grid(True, alpha=0.3)

    # ============================================================
    # 2. Ingresos mensuales
    # ============================================================
    ax = axes[1]
    ax.bar(df["t"], df["Ingresos"], alpha=0.8)
    ax.axvline(12.5, linestyle="--", linewidth=1)
    ax.set_title("Ingresos mensuales")
    ax.set_xlabel("Mes")
    ax.set_ylabel("USD")
    ax.yaxis.set_major_formatter(mticker.FuncFormatter(formato_usd))
    ax.grid(True, alpha=0.3)

    # ============================================================
    # 3. Costos, CAC y EBITDA
    # ============================================================
    ax = axes[2]
    ax.plot(df["t"], df["Costo_operacional"], linewidth=2, label="Costo operacional")
    ax.plot(df["t"], df["CAC"], linewidth=2, label="CAC")
    ax.plot(df["t"], df["G_adm"] + df["RRHH"], linewidth=2, label="G. adm. + RRHH")
    ax.bar(df["t"], df["EBITDA"], alpha=0.35, label="EBITDA")
    ax.axhline(0, linewidth=1)
    ax.axvline(12.5, linestyle="--", linewidth=1)
    ax.set_title("Costos, CAC y EBITDA")
    ax.set_xlabel("Mes")
    ax.set_ylabel("USD")
    ax.yaxis.set_major_formatter(mticker.FuncFormatter(formato_usd))
    ax.legend()
    ax.grid(True, alpha=0.3)

    # ============================================================
    # 4. Caja acumulada
    # ============================================================
    ax = axes[3]
    ax.plot(df["t"], df["Caja"], linewidth=2, label="Caja acumulada")
    ax.axhline(0, linewidth=1)
    ax.axvline(12.5, linestyle="--", linewidth=1)
    ax.set_title("Caja acumulada")
    ax.set_xlabel("Mes")
    ax.set_ylabel("USD")
    ax.yaxis.set_major_formatter(mticker.FuncFormatter(formato_usd))
    ax.legend()
    ax.grid(True, alpha=0.3)

    # ============================================================
    # 5. Servicios nuevos vs recurrentes
    # ============================================================
    ax = axes[4]
    ax.stackplot(
        df["t"],
        df["Adq_clientes"],
        df["Ventas_recurrentes"],
        labels=["Servicios nuevos", "Servicios recurrentes"],
        alpha=0.8
    )
    ax.axvline(12.5, linestyle="--", linewidth=1)
    ax.set_title("Servicios nuevos vs recurrentes")
    ax.set_xlabel("Mes")
    ax.set_ylabel("Servicios")
    ax.legend()
    ax.grid(True, alpha=0.3)

    # ============================================================
    # 6. Resumen DCF
    # ============================================================
    ax = axes[5]
    ax.axis("off")

    if resultados_dcf is not None:
        van = resultados_dcf.get("VAN", np.nan)
        vp_flujos = resultados_dcf.get("vp_flujos", np.nan)
        vd_vp = resultados_dcf.get("valor_desecho_vp", np.nan)

        texto = (
            "Resumen DCF\n\n"
            f"Capital inicial: USD {inst['VC']:,.0f}\n"
            f"VP flujos: USD {vp_flujos:,.0f}\n"
            f"VP valor residual: USD {vd_vp:,.0f}\n"
            f"VAN: USD {van:,.0f}\n"
            f"Tasa anual: {inst['beta_anual']*100:.1f}%"
        )
    else:
        texto = "Resumen DCF no disponible"

    ax.text(
        0.05, 0.85, texto,
        transform=ax.transAxes,
        fontsize=12,
        verticalalignment="top",
        bbox=dict(boxstyle="round", alpha=0.15)
    )

    fig.suptitle("Plan de Crecimiento Acelerado — Resultados del Modelo", fontsize=16, fontweight="bold")
    fig.tight_layout(rect=[0, 0.02, 1, 0.96])

    plt.savefig(filename, dpi=150, bbox_inches="tight")
    print(f"Visualizaciones guardadas en: {filename}")

    return fig

fig = generar_visualizaciones(
    df_resultados,
    instancia,
    resultados_dcf=resultados_dcf,
    df_unit_economics=df_unit_economics,
    filename="visualizaciones_pca.png"
)

import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import matplotlib.gridspec as gridspec
from matplotlib.patches import FancyBboxPatch
import numpy as np

def generar_visualizaciones(df, inst, resultados_dcf=None, df_unit_economics=None, filename="visualizaciones_pca.png"):
    """
    Genera un dashboard con los resultados clave del plan óptimo.
    """
    H = inst["H"]
    T = list(range(1, H + 1))

    fig = plt.figure(figsize=(18, 20))
    fig.patch.set_facecolor('#0f1117')
    gs = gridspec.GridSpec(4, 3, figure=fig, hspace=0.45, wspace=0.35)

    COLOR_BG = '#0f1117'
    COLOR_PANEL = '#1a1d27'
    COLOR_ACCENT = '#4f8ef7'
    COLOR_GREEN = '#2ecc71'
    COLOR_RED = '#e74c3c'
    COLOR_YELLOW = '#f39c12'
    COLOR_PURPLE = '#9b59b6'
    GRID_COLOR = '#2a2d3a'
    TEXT_COLOR = '#e0e0e0'

    def style_ax(ax, title):
        ax.set_facecolor(COLOR_PANEL)
        ax.tick_params(colors=TEXT_COLOR, labelsize=8)
        ax.spines[['top', 'right', 'left', 'bottom']].set_color(GRID_COLOR)
        ax.xaxis.label.set_color(TEXT_COLOR)
        ax.yaxis.label.set_color(TEXT_COLOR)
        ax.set_title(title, color=TEXT_COLOR, fontsize=10, fontweight='bold', pad=8)
        ax.grid(True, color=GRID_COLOR, alpha=0.5, linewidth=0.5)
        ax.yaxis.set_major_formatter(mticker.FuncFormatter(
            lambda x, _: f'{x:,.0f}'))
        ax.xaxis.set_major_formatter(mticker.FuncFormatter(
            lambda x, _: f'{int(x)}'))

    fig.suptitle("PLAN DE CRECIMIENTO ACELERADO — RESULTADOS ÓPTIMOS",
                 color='white', fontsize=14, fontweight='bold', y=0.98)

    # 1. Flujo de Clientes
    ax1 = fig.add_subplot(gs[0, :2])
    style_ax(ax1, "1. Flujo de Clientes (mensual)")
    ax1.fill_between(df["t"], df["Clientes_activos"], alpha=0.3, color=COLOR_ACCENT, label="Clientes activos")
    ax1.plot(df["t"], df["Clientes_activos"], color=COLOR_ACCENT, linewidth=2)
    ax1.bar(df["t"], df["Adq_clientes"], alpha=0.7, color=COLOR_GREEN, label="Adquisición", width=0.8)
    # Proxy para churn, asumiendo un % constante de clientes activos
    ax1.bar(df["t"], -df["Clientes_activos"] * inst["churn_mensual"][(0, 1)], alpha=0.5, color=COLOR_RED, label="Churn (proxy)", width=0.8)
    ax1.axvline(12.5, color=COLOR_YELLOW, linestyle='--', alpha=0.7, label="Fin plan base")
    ax1.set_xlabel("Mes")
    ax1.set_ylabel("Clientes")
    ax1.legend(loc='upper left', fontsize=8, facecolor=COLOR_PANEL,
               labelcolor=TEXT_COLOR, framealpha=0.8)

    # 2. Flujo de Ingresos
    ax2 = fig.add_subplot(gs[0, 2])
    style_ax(ax2, "2. Ingresos por Año (USD)")
    anual = df.groupby("Año")["Ingresos"].sum()
    bars = ax2.bar(anual.index, anual.values, color=[COLOR_ACCENT, COLOR_GREEN, COLOR_PURPLE])
    for bar, val in zip(bars, anual.values):
        ax2.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + anual.max() * 0.02,
                 f'{val:,.0f}', ha='center', va='bottom', color=TEXT_COLOR, fontsize=8)
    ax2.set_xlabel("Año")
    ax2.set_ylabel("USD")
    ax2.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'{x:,.0f}'))

    # 3. EBITDA mensual y Caja Acumulada
    ax3 = fig.add_subplot(gs[1, :2])
    style_ax(ax3, "3. EBITDA Mensual y Caja Acumulada (USD)")
    colors_ebitda = [COLOR_GREEN if v >= 0 else COLOR_RED for v in df["EBITDA"]]
    ax3.bar(df["t"], df["EBITDA"], color=colors_ebitda, alpha=0.8, width=0.8, label="EBITDA")
    ax3_twin = ax3.twinx()
    ax3_twin.plot(df["t"], df["Caja"], color=COLOR_YELLOW, linewidth=2, label="Caja")
    ax3_twin.tick_params(colors=TEXT_COLOR, labelsize=8)
    ax3_twin.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'{x:,.0f}'))
    ax3_twin.spines[['top', 'right', 'left', 'bottom']].set_color(GRID_COLOR)
    ax3_twin.yaxis.label.set_color(COLOR_YELLOW)
    ax3.axhline(0, color='white', linewidth=0.5, linestyle='--')
    ax3.axvline(12.5, color=COLOR_YELLOW, linestyle='--', alpha=0.5)
    ax3.set_xlabel("Mes")
    ax3.set_ylabel("EBITDA (USD)", color=TEXT_COLOR)
    ax3_twin.set_ylabel("Caja (USD)", color=COLOR_YELLOW)
    lines1, labels1 = ax3.get_legend_handles_labels()
    lines2, labels2 = ax3_twin.get_legend_handles_labels()
    ax3.legend(lines1 + lines2, labels1 + labels2, loc='lower right',
               fontsize=8, facecolor=COLOR_PANEL, labelcolor=TEXT_COLOR)

    # 4. Fuerza de ventas
    ax4 = fig.add_subplot(gs[1, 2])
    style_ax(ax4, "4. Fuerza de Ventas")
    ax4.step(df["t"], df["Vendedores"], where='post', color=COLOR_ACCENT, linewidth=2, label="Vendedores")
    ax4.step(df["t"], df["Lideres"], where='post', color=COLOR_PURPLE, linewidth=2, label="Líderes")
    ax4.set_xlabel("Mes")
    ax4.set_ylabel("# Personas")
    ax4.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'{x:.0f}'))
    ax4.legend(fontsize=8, facecolor=COLOR_PANEL, labelcolor=TEXT_COLOR)

    # 5. Servicios nuevos vs recurrentes
    ax5 = fig.add_subplot(gs[2, :2])
    style_ax(ax5, "5. Servicios: Nuevos vs Recurrentes (mensual)")
    ax5.stackplot(df["t"], df["Adq_clientes"], df["Ventas_recurrentes"],
                  labels=["Nuevos", "Recurrentes"],
                  colors=[COLOR_ACCENT, COLOR_GREEN], alpha=0.8)
    ax5.axvline(12.5, color=COLOR_YELLOW, linestyle='--', alpha=0.7)
    ax5.set_xlabel("Mes")
    ax5.set_ylabel("Servicios")
    ax5.legend(loc='upper left', fontsize=8, facecolor=COLOR_PANEL, labelcolor=TEXT_COLOR)

    # 6. Flujo de caja DCF
    ax6 = fig.add_subplot(gs[2, 2])
    style_ax(ax6, "6. Flujo Caja Descontado por Año (USD)")
    if resultados_dcf and "df_flujo_caja" in resultados_dcf:
        df_fc = resultados_dcf["df_flujo_caja"]
        # Ensure 'Año' column is integer for grouping
        df_fc['Año'] = df_fc['Año'].astype(int)
        fc_anual = df_fc.groupby("Año")["FC_desc"].sum()
        colors_fc = [COLOR_GREEN if v >= 0 else COLOR_RED for v in fc_anual.values]
        ax6.bar(fc_anual.index, fc_anual.values, color=colors_fc, alpha=0.8)
        ax6.set_xlabel("Año")
        ax6.set_ylabel("USD")
    else:
        ax6.text(0.5, 0.5, "DCF Data Not Available", horizontalalignment='center', verticalalignment='center', transform=ax6.transAxes, color=TEXT_COLOR)
    ax6.axhline(0, color='white', linewidth=0.5)
    ax6.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'{x:,.0f}'))

    # 7. KPI Cards (fila inferior)
    ax7 = fig.add_subplot(gs[3, :])
    ax7.set_facecolor(COLOR_BG)
    ax7.axis('off')

    kpis = []
    if resultados_dcf:
        kpis.append(("VAN (DCF)", f"USD {resultados_dcf['VAN']:,.0f}", COLOR_GREEN if resultados_dcf['VAN'] > 0 else COLOR_RED))
    if df_unit_economics is not None:
        # Extract values for specific KPIs using the 'df_unit_economics' DataFrame
        ue_dict = df_unit_economics.set_index('Unit Economic')['Valor'].to_dict()
        ue_churn = next((item['Valor'] for item in df_unit_economics.to_dict('records') if item['Unit Economic'] == 'CHURN'), np.nan)
        ue_mom_growth = next((item['Valor'] for item in df_unit_economics.to_dict('records') if item['Unit Economic'] == 'MoM Growth'), np.nan)
        ue_ltv = next((item['Valor'] for item in df_unit_economics.to_dict('records') if item['Unit Economic'] == 'LTV'), np.nan)
        ue_cac = next((item['Valor'] for item in df_unit_economics.to_dict('records') if item['Unit Economic'] == 'CAC'), np.nan)
        ue_ltv_cac = next((item['Valor'] for item in df_unit_economics.to_dict('records') if item['Unit Economic'] == 'LTV/CAC'), np.nan)
        ue_arr_pct = next((item['Valor'] for item in df_unit_economics.to_dict('records') if item['Unit Economic'] == 'ARR'), np.nan)
        ue_gp = next((item['Valor'] for item in df_unit_economics.to_dict('records') if item['Unit Economic'] == 'Gross Profit (GP)'), np.nan)

        kpis.extend([
            ("LTV", f"USD {ue_ltv:,.0f}", COLOR_ACCENT),
            ("CAC", f"USD {ue_cac:,.0f}", COLOR_YELLOW),
            ("LTV/CAC", f"{ue_ltv_cac:.1f}x", COLOR_GREEN if ue_ltv_cac >= 3 else COLOR_RED),
            ("ARR%", f"{ue_arr_pct*100:.1f}%", COLOR_PURPLE),
            ("Gross Profit", f"{ue_gp*100:.1f}%", COLOR_GREEN),
            ("MoM Growth", f"{ue_mom_growth*100:.1f}%", COLOR_ACCENT)
        ])
    kpis.append(("Capital Trabajo", f"USD {inst['VC']:,.0f}", COLOR_YELLOW))

    n_kpis = len(kpis)
    if n_kpis > 0:
        for i, (label, value, color) in enumerate(kpis):
            x = i / n_kpis
            w = 1 / n_kpis
            rect = FancyBboxPatch((x + 0.005, 0.05), w - 0.01, 0.9,
                                   boxstyle="round,pad=0.02",
                                   facecolor=COLOR_PANEL, edgecolor=color,
                                   linewidth=2, transform=ax7.transAxes)
            ax7.add_patch(rect)
            ax7.text(x + w / 2, 0.68, label, ha='center', va='center',
                     color=TEXT_COLOR, fontsize=9, transform=ax7.transAxes)
            ax7.text(x + w / 2, 0.32, value, ha='center', va='center',
                     color=color, fontsize=11, fontweight='bold', transform=ax7.transAxes)
    else:
        ax7.text(0.5, 0.5, "KPIs Not Available", horizontalalignment='center', verticalalignment='center', transform=ax7.transAxes, color=TEXT_COLOR, fontsize=12)

    fig.tight_layout(rect=[0, 0.02, 1, 0.96])

    plt.savefig(filename, dpi=150, bbox_inches="tight", facecolor=COLOR_BG)
    print(f"Visualizaciones guardadas en: {filename}")

    return fig

fig = generar_visualizaciones(
    df_resultados,
    instancia,
    resultados_dcf=resultados_dcf,
    df_unit_economics=df_unit_economics,
    filename="visualizaciones_pca.png"
)

"""

## 9. Flujo integrado

Para mejorar la estructura del código y facilitar su ejecución, se ha creado una función `run_optimization_pipeline` que orquesta todos los pasos del modelo. Esta función carga los parámetros, genera la instancia, resuelve el modelo, extrae y muestra los resultados, realiza las valorizaciones (DCF y Múltiplos), calcula los unit economics y genera las visualizaciones."""

def run_optimization_pipeline(verbose_solver=False):
    """
    Orquesta el pipeline completo del modelo de optimización.
    Carga parámetros, genera la instancia, resuelve el modelo,
    extrae y muestra resultados, realiza valorización,
    calcula unit economics y genera visualizaciones.
    """
    print("═" * 80)
    print("  EJECUTANDO PIPELINE COMPLETO")
    print("═" * 80)

    # 1. Cargar parámetros base
    print("\nPASO 1: Cargar parámetros base")
    parametros = cargar_parametros_base()

    # 2. Generar instancia del modelo
    print("\nPASO 2: Generar instancia del modelo")
    instancia = generar_instancia(parametros)
    mostrar_resumen_instancia(instancia)

    # 3. Construir y resolver el modelo de optimización
    print("\nPASO 3: Construir y resolver el modelo")
    status, prob, variables = construir_y_resolver_modelo(
        instancia, verbose=verbose_solver
    )

    if status not in ["Optimal"]:
        print(f"\n  ⚠ El modelo resultó {status}. No se pudo generar un plan óptimo.")
        print("  Sugerencias para resolver:")
        print("  - Aumentar 'VC' (Capital Inicial)")
        print("  - Reducir 'A_base' (clientes a adquirir en el plan base)")
        print("  - Reducir 'g_adm' o 'RRHH_mensual'")
        print("  - Ajustar 'beta' (tasa de descuento)")
        return None

    # 4. Extraer resultados del modelo
    print("\nPASO 4: Extraer resultados")
    df_resultados = extraer_resultados(instancia, variables)
    imprimir_resultados_mvp(df_resultados, instancia)

    # 5. Calcular valorización por DCF
    print("\nPASO 5: Calcular valorización por DCF")
    resultados_dcf = calcular_valorizacion_dcf(df_resultados, instancia)

    # 6. Calcular valorización por Múltiplos
    print("\nPASO 6: Calcular valorización por Múltiplos")
    resultados_multiplos = calcular_valorizacion_multiplos(df_resultados, instancia)

    # 7. Calcular Unit Economics
    print("\nPASO 7: Calcular Unit Economics")
    df_unit_economics = calcular_unit_economics(
        df_resultados, instancia, resultados_dcf
    )

    # 8. Generar visualizaciones
    print("\nPASO 8: Generar visualizaciones")
    try:
        fig = generar_visualizaciones(
            df_resultados,
            instancia,
            resultados_dcf=resultados_dcf,
            df_unit_economics=df_unit_economics,
            filename="plan_optimo_dashboard.png"
        )
    except Exception as e:
        print(f"  ⚠ Error al generar visualizaciones: {e}")
        fig = None

    print("═" * 80)
    print("  PIPELINE COMPLETADO EXITOSAMENTE")
    print(f"  VAN (DCF): USD {resultados_dcf['VAN']:,.0f}")
    print(f"  Solver Status: {status}")
    if fig:
        print("  Dashboard guardado como: plan_optimo_dashboard.png")
    print("═" * 80)

    return {
        "parametros": parametros,
        "instancia": instancia,
        "status": status,
        "prob": prob,
        "variables": variables,
        "df_resultados": df_resultados,
        "resultados_dcf": resultados_dcf,
        "resultados_multiplos": resultados_multiplos,
        "df_unit_economics": df_unit_economics,
        "fig": fig,
    }

# Ejecutar el pipeline completo
full_pipeline_results = run_optimization_pipeline(verbose_solver=False)

"""## 10. Supuestos, decisiones de modelado y limitaciones de MVP

### Supuestos operacionales

* Base temporal mensual. Valores monetarios en USD.
* Un cliente adquirido genera exactamente una venta nueva en el período de adquisición.
* La recurrencia es mensual (frecuencia=1): cada cliente activo genera ingresos cada mes.
* La supervivencia de cohortes es determinista: φ(τ,t) = ∏(1 − churn_m[c]) para c ∈ (τ,t].
* El churn se parametriza como tasa anual y se convierte a mensual mediante
churn_m = 1 − (1 − churn_a)^(1/12). Se asume uniforme dentro del año.
* α = 1: todos los clientes activos elegibles recompran en cada período (frecuencia=1).
* El plan de adquisición de los primeros 12 meses es exógeno y fijo (consensuado con el cliente).
* Los vendedores y líderes comerciales son variables enteras (no se puede contratar
una fracción de persona).
* La fuerza comercial es monotónica: no se despiden vendedores ni líderes durante el horizonte.

### Decisiones de modelado

* Adquisición como variable de decisión (períodos 13–36):
* El modelo decide cuántos clientes adquirir en cada período posterior al plan base.
* El MoM emerge como consecuencia, no como input. Esto permite que el solver encuentre
el plan óptimo dentro de las restricciones financieras y comerciales.
* Suavizamiento por media móvil (R1b):
La adquisición post-año 1 no puede superar (1 + g_max)/3 × MA3(A[t-1], A[t-2], A[t-3]).
Fundamento: el plan futuro debe mantener continuidad con la tendencia del plan consensuado.
No es un tope de mercado; es una restricción de plausibilidad operacional.
* g_max = 0.15 implica un crecimiento máximo del 15% mensual sobre la tendencia reciente.
* Costos operacionales por escalones:
Cost_op[t] ≥ max(c_u × Q[t], c_min × m_op[t]).
Refleja que los costos de infraestructura tienen componentes fijos por capacidad instalada
y variables por uso. El escalón m_op es entero y crece cuando Q supera u_max por escalón.
* Caja libre (sin restricción de piso en MVP):
La restricción Caja[t] ≥ 0 genera infactibilidad estructural porque el plan base
año 1 consume más capital del VC disponible.

* Valor terminal por múltiplo de revenue:
Se usa múltiplo × Revenue Año 3, descontado al presente. No se usa perpetuidad de EBITDA
porque en startups el EBITDA del último mes puede ser bajo o negativo, subestimando el valor.

### Limitaciones del modelo MVP

* No modela límite de mercado (TAM): el crecimiento solo está acotado por la
restricción 3 y la capacidad comercial. Una versión futura incorporaría una
curva logística como la curva de adopción de tecnología en forma explícita (Rogers, 1962).
* Churn exógeno: la tasa de churn es un parámetro fijo por año. No captura
que el churn podría reducirse con inversión en retención o aumentar si el ticket
sube. La endogeneización del churn requeriría un modelo no lineal.
* Sin múltiples servicios activos: cada cliente se asocia a un único servicio
en MVP. La extensión a múltiples servicios está preparada en la estructura del
código (índice s) pero no ha sido validada con instancias reales.
* Sin deuda ni estructura de capital: el modelo no considera deuda, dilución
de equity ni rondas de inversión futuras. El VC es el único capital disponible.
* Impuestos en postprocesamiento: los impuestos no entran en el solver.
* Gastos administrativos fijos: g_adm no escala con el crecimiento de la empresa.
En la práctica, sobre cierto nivel de operación se requiere escalar estructura
administrativa. Extensión futura: escalones en g_adm similares a costos operacionales.
* Fuerza de ventas como único canal de CAC: no se modela publicidad ni canales
digitales.
"""